### ISSUE TITLE
Jobs mode: use webhook to send responses back to steward?

### ISSUE THREAD

**Issue by krancour** [deis/steward#169]
Currently, in jobs modes, containerized operations receive their responses through the container's stdout. Especially with respect to bind operations, this is probably a bad idea that results in a vulnerability. All too often, logs are collected from containers' stdout and stderr using the likes of logspout or fluentd. In any cluster where this is the case, the credentials that are included in a binding response could bleed into logs where they could possibly be discovered by unauthorized parties.

One proposed alternative is that responses be communicated back to steward by means of a web hook. While I dislike the additional complexity, I think this might be quite necessary in the name of security.

For consistency, I would propose that this approach be applied to _all_ the containerized operations (not just bind).

I am very, very open to simpler alternatives if anyone has one.

**Comment by slack** [comment]
> 1. Will the pod be given the steward pod's IP address?

Should probably be the cluster FQDN for the steward service address.

> 2. What should the pod do if the launching steward crashes while it's running?

POST with retry + backoff until a configured deadline. Broker's responsibility to rollback any changes?

**Comment by arschles** [comment]
>Should probably be the cluster FQDN for the steward service address.

stewards don't currently run behind services; I don't feel it's worth running a service just for command mode, but might be necessary...

>POST with retry + backoff until a configured deadline. Broker's responsibility to rollback any changes?

both are good with me

**Comment by arschles** [comment]
Since we are going to be focusing on using the CF broker API for now (see https://github.com/kubernetes-incubator/service-catalog/pull/31), I'm going to close this issue. To be re-opened if we once again pursue command (previously jobs) mode.
