### ISSUE TITLE
Proposal: cmd mode-- accelerate timeout when a pod looks like it will fail

### ISSUE THREAD

**Issue by krancour** [deis/steward#214]
See discussion in #207

In cmd mode, it's possible for a pod that is executing a discrete action to enter a state from which it has little or no chance of recovering and completing successfully. In such cases, it might be prudent to detect these conditions, possibly accelerate the timeout (rather than just give up entirely), and return an error.

This is issue isn't a priority atm.

**Comment by arschles** [comment]
We've split steward into [steward-framework](https://github.com/deis/steward-framework), the Go SDK for Kubernetes resources and control loops, and [steward-cf](https://github.com/deis/steward-cf), the CF broker API implementation on top of steward-framework.

If and when we create a steward-cmd, which would be a command-mode implementation on top of steward-framework, we should reconsider this; closing.
