### ISSUE TITLE
Proposal: steward-manager process

### ISSUE THREAD

**Issue by slack** [deis/steward#215]
Given that we expect to deploy many stewards to a given cluster it may make sense to offload janitorial work to a dedicated "manager" process. This process could provide:
- GC for `ServiceCatalogEntries` that are no longer backed by a `steward`
- Aggregation point for data and logs: operational logs, audit logs, claim provisioning data, etc.
- Monitoring deployed stewards, etc.

Relates to #14, #212

**Comment by arschles** [comment]
@slack given the new architecture described at https://github.com/kubernetes-incubator/service-catalog/pull/31, is this issue still relevant?

**Comment by krancour** [comment]
imo, here's how each of the bullet points in the OP is affected by the re-architecture:

> - GC for `ServiceCatalogEntries` that are no longer backed by a `steward`

This could simply be another control loop within the new Steward Framework. i.e. There may not be a need for a separately deployable component to address this.

> - Aggregation point for data and logs: operational logs, audit logs, claim provisioning data, etc.

This implicitly exists already with the new architecture.

> - Monitoring deployed stewards, etc.

This too might be moot with the new architecture, although monitoring the health of backing brokers could be a concern instead. This too could be accommodated with another control loop.

Personally, I'd move that we close this and open new, more focused issues in Steward Framework for any of the above that we agree remains a concern.

**Comment by slack** [comment]
Sounds good.
