### ISSUE TITLE
Proposal: Model our UX after k8s PVs / PVCs

### ISSUE THREAD

**Issue by krancour** [deis/steward#216]
**UPDATE:** This proposal is now available as a [slide deck](https://docs.google.com/presentation/d/1Fm3qG9zQ4R8ZbhtTObmQjO3UZYJ0ruYI4qr5w_gEKN8/edit?usp=sharing), complete with diagrams and examples. This is the deck that was presented to SIG Service Catalog on 2016-10-10.

See #212, #213, and #215

I believe this to be a tenable proposal for addressing the issues referenced above as well as the more complex use cases I articulated in #213 which are not currently addressed by any other proposal.

For further reference: http://kubernetes.io/docs/user-guide/persistent-volumes/

In k8s, `PersistentVolumes` are resources that describe an actual NFS (or similar). `PersistantVolumeClaims` are requests for the allocation of those resources. To illustrate a similarity to what we're trying to accomplish with Steward, `PersistentVolumes` can be provisioned in one of two ways:

**Dynamic:**

> When none of the static PVs the administrator created matches a user’s PersistentVolumeClaim, the cluster may try to dynamically provision a volume specially for the PVC. This provisioning is based on StorageClasses: the PVC must request a class and the administrator must have created and configured that class in order for dynamic provisioning to occur.

There is a striking similarity here between a `StorageClass` and a `ServiceCatalogEntry`. Neither describes an _instance_ of a volume or service. They describe a _kind_ of volume or service-- a recipe for dynamic instantiation. I'm drawing a parallel here between dynamically provisioned `PersistentVolumes` and our notion of "dedicated" services (which live and die with a consumer's claim on them).

**Static:**

> A cluster administrator creates a number of PVs. They carry the details of the real storage which is available for use by cluster users. They exist in the Kubernetes API and are available for consumption.

Note the similarity to our notion of "multi-tenant" services. Just as an administrator creates specific, named `PersistentVolumes` for consumption by apps making `PersistentVolumeClaims` upon those resources, we are imagining that administrators (operators) pre-define multi-tenant services for consumption by apps making `ServicePlanClaims`.

If we are appreciative of symmetry and consistency, what Steward currently lacks vis a vis PVs / PVCs is that we don't have a `PersistentVolume`-like resource type that can represent existing (multi-tenant) services. Were we to introduce a `Service` type, we'd get that symmetry and consistency _and_ we would address the use cases I brought up in ~~my previous post~~ #213.

**Point of clarification:** We all know the term "Service" is overloaded. Please forgive my use of `Service` above (and repeatedly in the following paragraphs). I'm not talking about a k8s `Service` (load balancer). I am talking about a hypothetical k8s resource type (3PR), instances of which are _representations_ of actual (sorry -->) _service_  instances. Obviously, we need to come up with a different name for this hypothetical resource type.

**What I'm actually proposing and _how_ it solves some problems:**

**ServiceClass**: (formerly `ServiceCatalogEntry`). Admins / operators create these _explicitly_ to describe a kind of service that _can_ be instantiated. These can reference a service id and plan id (existing concepts) that are found in some Steward's own internal catalog. That Steward can and will remain responsible for managing provisioning.

A couple really great things this accomplishes:
1. `Services` or `ServiceClaims` (formerly `ServicePlanClaims`) can reference semantically meaningful names chosen by an administrator-- names like "Postgres small." The consumer needs to know nothing of _how_ that is fulfilled (whether it is through RDS or something else is not necessarily evident, and probably irrelevant). The consumer doesn't need to _ever_ deal with long, opaque service ids and plan ids.
2. The administrator can constrain or restrict any given broker's offerings-- just because the RDS broker offers SQL Server doesn't mean I want to make it available in my cluster. 😉 

**Services:** (again, excuse the overloading). Admins / operators create these _explicitly_ and give them semantically meaningful names (e.g. "zip code database (postgres)"). They reference a `ServiceClass`. The Steward(s) that can handle provisioning for the service id and plan id referenced by that  `ServiceClass` will provision such a service when a `Service` resource is created and deprovision it when it is deleted. (See #212)

**ServiceClaims**: (formerly `ServicePlanClaims`). These reference an existing, multi-tentant `Service` _by name_ (e.g. "zip code database"), _or_ request a dedicated service instance by referencing a `ServiceClass` by name. In the former case, internally, only binding is necessary. In the latter case, internally, provisioning and binding must both occur. In both cases, these discrete, internal operations are handled by the Steward(s) that can handle service id and plan id referenced by that  `ServiceClass`.

Note that much of the above is probably further impetus for the creation of a "Steward Manager" (as @slack also has proposed in #215). This would handle the lifecycle of k8s resources discussed above, manage all Stewards, and delegate discrete operations to individual Stewards. (Essentially, then, each individual Steward just becomes a "broker adapter" (of sorts) that can extend the sort of `ServiceClasses` an operator would be able to define _without_ having to restart / reconfigure the whole system.)

From an operator perspective, this all looks great-- eventually, we (or the community) could offer Helm charts of a Steward pre-configured and bundled up with its backing broker. The chart can _also_ include `ServiceClass` resources for all of (or a subset of) the backing broker's offerings. Operators can edit the chart to remove `ServiceClasses` they don't want to expose. Operators can also make their own custom charts that describe their multi-tenant services by referencing `ServiceClasses`.

From a consumer perspective, this is also very simple: make a `ServiceClaim` and reference either a multi-tenant `Service` by name or a `ServiceClass` by name.

cc @gabrtv @arschles @slack

**Comment by arschles** [comment]
The SIG has decided on an API that is loosely related to the PV/PVC system, along with other elements. See https://github.com/kubernetes-incubator/service-catalog/pull/31 for details. I'm closing this issue.
