### ISSUE TITLE
Proposal: support catalog filtering/manipulation in CF mode

### ISSUE THREAD

**Issue by slack** [deis/steward#229]
There are a few cases when deploying a steward in front of a CF broker where the operator may want to filter or manipulate catalog entries from the broker before publishing to the Service Catalog.
- whitelist: pass through services and plans that match a whitelist, deny everything else
- blacklist: drop specific service and plan entries that match, allow everything else
- remap (optional): map service/plan pair from CF to a new service/plan pair in the Service Catalog

Remap is probably the most controversial addition and is most likely optional until someone reeealy needs it.

**Comment by arschles** [comment]
If we go forward with the [`ServiceClass` based catalog/claims architecture](https://docs.google.com/presentation/d/1Fm3qG9zQ4R8ZbhtTObmQjO3UZYJ0ruYI4qr5w_gEKN8/edit?ts=57f7112d#slide=id.g178ca94ec8_0_113), I'd like to see a separate process tool (`steward-cf-lister`?) that does the following:

1. Calls the broker's catalog endpoint
2. Applies the whitelist & blacklist
3. Writes each selected (service, plan) pair to the set of `ServiceClass`es

I'd to like to see this separate tool for the following reasons:

1. It maps more closely to the `cf` CLI tool (could even be implemented as a CLI itself)
2. It removes the `ServiceClass` publishing logic from steward itself

**Comment by krancour** [comment]
Is there a reason this is scoped only to CF mode? Wouldn't we want to use this mechanism to filter offerings regardless of mode?

**Comment by arschles** [comment]
given the following:

1. operators manually enter the catalog entry/entries in helm mode
2. https://github.com/deis/steward/issues/228 proposes that operators manually enter catalog entries in cmd mode

if #228 goes forward, this would no longer apply to helm mode. otherwise, I generally agree with adding it to cmd mode @krancour

**Comment by arschles** [comment]
This issue was replaced by https://github.com/deis/steward-cf/issues/7; closing.
