### ISSUE TITLE
Bug: Non-string data in binding responses causes error

### ISSUE THREAD

**Issue by krancour** [deis/steward#231]
The JSON response from a binding operation, which contains connection details and credentials, might include non-string fields, e.g. port as an integer. When it does, this error is seen:

```
status: failed
status-description: 'json: cannot unmarshal number into Go value of type string'
```

**Comment by arschles** [comment]
good find - we might have to change the `Creds` field of the binding response to be a `map[string]interface{}`.

implementor's note: that `Creds` field is currently a `JSONObject` type. `JSONObject` is an alias for `map[string]string`, but used in a variety of different locations. chainging `JSONObject` to `map[string]interface{}` can have far-reaching effects
