### ISSUE TITLE
[Meta] Split k8s packages into a new project

### ISSUE THREAD

**Issue by arschles** [deis/steward#240]
This meta-issue is for:
- Moving the Kubernetes and event loop related packages into a new repository (and hence, new Go package)
- Adapting the aforementioned code to work with the new data structures and API defined in https://github.com/kubernetes-incubator/service-catalog/pull/13

After this issue has been completed, future work (to be detailed in a new issue) is to:
- Build a CloudFoundry service broker API compatible controller based on this new library
- Propose upstreaming this new library to the the [service-broker repository](https://github.com/kubernetes-incubator/service-catalog) in the incubator

**Comment by arschles** [comment]
cc/ @krancour @slack

**Comment by krancour** [comment]
@arschles @slack any thoughts on how we name things?

Could I propose the following project names? (I think it's self evident what goes in each.)

* deis/steward-framework
* deis/steward-cf

What's not clear to me is which of those two is the former `deis/steward`. I could see arguments for both.

**Comment by arschles** [comment]
I'm fine with those names for now, and it's clear what goes in each. I think it's ok that it's unclear which is the former `deis/steward` - because neither really is.

**Comment by krancour** [comment]
@arschles considerations, however, may we:

1. Which of those two do most open issues logically belong to?
1. Which of those two do we want existing followers redirected to?

**Comment by arschles** [comment]
I'd say bullets 1, 2 and 4 go into the `steward-framework` repo. Bullet 3 would go into the new `steward-cf` repo.

**Comment by arschles** [comment]
to answer your question _for real_ (I'm now realizing that my previous didn't answer anything you added):

1. I don't think there's any clear, hard & fast rule. IMO the issues that relate to the state machine and/or concurrency control should _mostly_ go into the framework repo, and the stuff about CF mode should go into deis/steward-cf. Stuff not related to CF mode or k8s stuff (i.e. helm mode) should prob stay in here
2. For now, can we have 2 new repos to defer this question for later? The answer is unclear at this point

**Comment by krancour** [comment]
Ack. Will start with two new repos.

**Comment by arschles** [comment]
This is done. https://github.com/krancour/steward-framework is the new repository, and it will be moved into the deis org shortly. closing
